"""
PRD Agent - Product Requirements Document Generator.

This agent generates detailed, engineer-focused Product Requirements Documents
that follow the EA repo's structured format with:
- YAML frontmatter for machine-parsing
- Traceability to existing requirements and decisions
- Integration with the ArchiMate/C4 architecture workflow
"""
import asyncio
from typing import AsyncIterator
from pathlib import Path
from claude_agent_sdk import (
    ClaudeSDKClient,
    ClaudeAgentOptions,
    AgentDefinition,
    AssistantMessage,
    ResultMessage,
    TextBlock,
)
from config import READONLY_TOOLS, EDIT_TOOLS, EA_REPO_ROOT


# Discovery questions for PRD generation
DISCOVERY_QUESTIONS = [
    "What problem are you trying to solve?",
    "Who are the primary users/stakeholders?",
    "What are the key functional requirements?",
    "What are the non-functional requirements (performance, security, scalability)?",
    "What systems or components will this interact with?",
    "Are there any technical constraints or dependencies?",
    "What's the expected timeline and priority?",
    "How will success be measured?",
]

PRD_TEMPLATE = """---
id: REQ-{req_id}
title: {title}
status: draft
owner: {owner}
created: {created_date}
updated: {created_date}
traces:
  decisions: []
  rfcs: []
  systems: {systems}
  views: []
tags: {tags}
---

# REQ-{req_id} — {title}

## Problem Statement
{problem_statement}

## Goals
{goals}

## Non-goals
{non_goals}

## Stakeholders
{stakeholders}

## Functional Requirements
{functional_requirements}

## Non-functional Requirements (NFRs)
{nfrs}

## Constraints
{constraints}

## Acceptance Criteria
{acceptance_criteria}

## Technical Design Considerations
{technical_considerations}

## Trace
- Impacts: [To be linked after RFC creation]
- Decisions: [To be linked after ADR creation]
- Views: [To be linked after diagram updates]

---
*Generated by PRD Agent*
"""


class PRDAgent:
    """
    Agent for generating Product Requirements Documents.

    Uses discovery questions to extract requirements and generates
    structured PRD documents that integrate with the EA workflow.
    """

    def __init__(
        self,
        cwd: str | None = None,
        interactive: bool = True,
    ):
        self.cwd = cwd or str(EA_REPO_ROOT)
        self.interactive = interactive
        self.discovery_answers: dict[str, str] = {}

    def _create_system_prompt(self) -> str:
        return """You are a Product Requirements Document (PRD) specialist.

Your role is to:
1. Ask targeted discovery questions to understand requirements
2. Analyze existing codebase to identify integration points
3. Generate comprehensive, engineer-focused PRDs
4. Ensure traceability to existing architecture artifacts

When generating PRDs:
- Use clear, actionable language
- Include specific acceptance criteria
- Identify dependencies and constraints
- Consider non-functional requirements (security, performance, scalability)
- Link to existing systems and components where applicable

Output format should follow the EA repo's REQ template with YAML frontmatter."""

    def _create_analyzer_agent(self) -> AgentDefinition:
        """Create a subagent for codebase analysis."""
        return AgentDefinition(
            description="Analyzes codebase to identify integration points and existing patterns",
            prompt="""You are a codebase analyzer. Your job is to:
1. Search for existing components related to the feature
2. Identify integration points and dependencies
3. Find existing patterns that should be followed
4. Report any potential conflicts or considerations

Be thorough but concise. Focus on actionable insights.""",
            tools=READONLY_TOOLS,
        )

    async def generate_prd(
        self,
        feature_description: str,
        answers: dict[str, str] | None = None,
    ) -> AsyncIterator[dict]:
        """
        Generate a PRD for the given feature.

        Args:
            feature_description: Brief description of the feature
            answers: Optional pre-filled answers to discovery questions

        Yields:
            Status updates and the generated PRD
        """
        self.discovery_answers = answers or {}

        options = ClaudeAgentOptions(
            system_prompt=self._create_system_prompt(),
            allowed_tools=EDIT_TOOLS + ["Task"],
            permission_mode="acceptEdits",
            cwd=self.cwd,
            agents={
                "codebase-analyzer": self._create_analyzer_agent(),
            },
        )

        async with ClaudeSDKClient(options=options) as client:
            # Phase 1: Analyze existing codebase
            yield {"type": "phase", "phase": "analysis", "message": "Analyzing codebase..."}

            analysis_prompt = f"""Analyze this codebase for a new feature: {feature_description}

Use the codebase-analyzer agent to:
1. Find related existing code and patterns
2. Identify potential integration points
3. Check for existing requirements or decisions that might be relevant

Search in:
- docs/10-requirements/ for existing requirements
- docs/20-decisions/ for relevant ADRs
- docs/40-architecture/ for related architecture elements
- model/catalog/ for existing system definitions

Report your findings concisely."""

            await client.query(analysis_prompt)

            analysis_result = ""
            async for message in client.receive_response():
                if isinstance(message, AssistantMessage):
                    for block in message.content:
                        if isinstance(block, TextBlock):
                            analysis_result += block.text
                            yield {"type": "text", "phase": "analysis", "text": block.text}

            # Phase 2: Generate PRD
            yield {"type": "phase", "phase": "generation", "message": "Generating PRD..."}

            # Build context from discovery answers
            context_parts = [f"Feature: {feature_description}"]
            context_parts.append(f"\nCodebase Analysis:\n{analysis_result}")

            if self.discovery_answers:
                context_parts.append("\nDiscovery Answers:")
                for q, a in self.discovery_answers.items():
                    context_parts.append(f"- {q}: {a}")

            generation_prompt = f"""Generate a comprehensive Product Requirements Document (PRD) for:

{chr(10).join(context_parts)}

Requirements for the PRD:
1. Use YAML frontmatter with: id, title, status, owner, created, traces, tags
2. Include all standard sections: Problem, Goals, Non-goals, Stakeholders, Functional Requirements, NFRs, Constraints, Acceptance Criteria
3. Make requirements specific and testable
4. Include technical considerations based on the codebase analysis
5. Identify systems that will be impacted (for the traces.systems field)

Generate the complete PRD in markdown format.
If you need to save it to a file, use: docs/10-requirements/REQ-XXXX-{feature_description.lower().replace(' ', '-')[:30]}.md"""

            await client.query(generation_prompt)

            prd_content = ""
            async for message in client.receive_response():
                if isinstance(message, AssistantMessage):
                    for block in message.content:
                        if isinstance(block, TextBlock):
                            prd_content += block.text
                            yield {"type": "text", "phase": "generation", "text": block.text}

                if isinstance(message, ResultMessage):
                    yield {
                        "type": "result",
                        "is_error": message.is_error,
                        "duration_ms": message.duration_ms,
                        "cost_usd": message.total_cost_usd,
                    }

            yield {
                "type": "completed",
                "prd": prd_content,
                "message": "PRD generation completed",
            }


async def generate_prd(
    feature_description: str,
    cwd: str | None = None,
    answers: dict[str, str] | None = None,
) -> None:
    """
    Convenience function to generate a PRD and print results.

    Example:
        await generate_prd(
            feature_description="User authentication with OAuth2",
            answers={
                "What problem are you trying to solve?": "Users need secure login",
                "Who are the primary users/stakeholders?": "End users, security team",
            }
        )
    """
    agent = PRDAgent(cwd=cwd)

    print(f"\n{'='*60}")
    print(f"PRD Agent - Generating Requirements Document")
    print(f"Feature: {feature_description}")
    print(f"{'='*60}\n")

    async for event in agent.generate_prd(feature_description, answers):
        event_type = event.get("type")

        if event_type == "phase":
            print(f"\n[{event['phase'].upper()}] {event['message']}")

        elif event_type == "text":
            print(event["text"], end="", flush=True)

        elif event_type == "result":
            print(f"\n\n[Cost: ${event.get('cost_usd', 0):.4f}]")

        elif event_type == "completed":
            print(f"\n\n{'='*60}")
            print(f"PRD Generation Complete!")
            print(f"{'='*60}")


if __name__ == "__main__":
    # Example usage
    asyncio.run(generate_prd(
        feature_description="Architecture change tracking dashboard",
        answers={
            "What problem are you trying to solve?": "Teams need visibility into architecture changes across the organization",
            "Who are the primary users/stakeholders?": "Enterprise architects, platform teams, security team",
        }
    ))
